name: Continuous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: npm install --package-lock-only

      - name: Check types
        run: |
          npm run check-types

      - name: Lint
        run: |
          npm run lint

      - name: Package
        run: |
          npm run pkg

      - name: Get Version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscord-${{ env.VERSION }}-pr${{ github.event.number }}.vsix
          path: vscord-*.vsix
